# Generated by Django 6.0.1 on 2026-01-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_purchase_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='followed_up',
            field=models.BooleanField(default=False),
        ),
    ]
